version: '3'

services:
  mongodb:
    container_name: ebay-notifier-mongodb
    image: mongo:latest
    volumes:
      - ./docker-config/database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"

  mailcatcher:
    container_name: ebay-notifier-mailcatcher
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

  redis:
    container_name: ebay-notifier-redis
    image: redis:latest
    ports:
      - "6379:6379"

  node:
    depends_on:
      - mongodb
      - mailcatcher
      - redis
    container_name: ebay-notifier-node
    build:
       context: ./
    image: ebay-notifier-node:1.1
    volumes:
      - "./:/var/www"
    links:
      - "mongodb:mongodb"
      - "mailcatcher:mailcatcher"
      - "redis:redis"
    ports:
      - "3000:3000"
